import { ROLES } from "../types";

/**
 * Role-Based Access Control (RBAC) Permission Maps
 */
export const PERMISSIONS = {
  VIEW_DASHBOARD: "view:dashboard",
  VIEW_DIGITAL_TWIN: "view:digital_twin",
  VIEW_ALERTS: "view:alerts",
  VIEW_INCIDENTS: "view:incidents",
  VIEW_AI_ANALYSIS: "view:ai_analysis",
  VIEW_CYBER_DNA: "view:cyber_dna",
  VIEW_ATTACK_PATHS: "view:attack_paths",
  VIEW_WHAT_IF: "view:what_if",
  VIEW_RESPONSE: "view:response",
  VIEW_FORENSICS: "view:forensics",
  VIEW_REPORTS: "view:reports",

  // Privileged Capabilities
  MANAGE_AUTHORIZATION: "manage:authorization",
  EXECUTE_DEFENSIVE_ACTIONS: "execute:defensive_actions",
  ASSIGN_INCIDENTS: "assign:incidents",
  VIEW_AUDIT_LOGS: "view:audit_logs",
  MANAGE_DEVICES: "manage:devices",
  CONFIGURE_SECURITY: "configure:security"
};

const ROLE_PERMISSIONS = {
  [ROLES.SOC_ANALYST]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_DIGITAL_TWIN,
    PERMISSIONS.VIEW_ALERTS,
    PERMISSIONS.VIEW_INCIDENTS,
    PERMISSIONS.VIEW_AI_ANALYSIS,
    PERMISSIONS.VIEW_CYBER_DNA,
    PERMISSIONS.VIEW_ATTACK_PATHS,
    PERMISSIONS.VIEW_WHAT_IF,
    PERMISSIONS.VIEW_RESPONSE,
    PERMISSIONS.VIEW_FORENSICS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_DEVICES
  ],

  [ROLES.SOC_LEAD]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_DIGITAL_TWIN,
    PERMISSIONS.VIEW_ALERTS,
    PERMISSIONS.VIEW_INCIDENTS,
    PERMISSIONS.VIEW_AI_ANALYSIS,
    PERMISSIONS.VIEW_CYBER_DNA,
    PERMISSIONS.VIEW_ATTACK_PATHS,
    PERMISSIONS.VIEW_WHAT_IF,
    PERMISSIONS.VIEW_RESPONSE,
    PERMISSIONS.VIEW_FORENSICS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_AUTHORIZATION,
    PERMISSIONS.EXECUTE_DEFENSIVE_ACTIONS,
    PERMISSIONS.ASSIGN_INCIDENTS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.MANAGE_DEVICES
  ],

  [ROLES.CISO]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_DIGITAL_TWIN,
    PERMISSIONS.VIEW_ALERTS,
    PERMISSIONS.VIEW_INCIDENTS,
    PERMISSIONS.VIEW_AI_ANALYSIS,
    PERMISSIONS.VIEW_CYBER_DNA,
    PERMISSIONS.VIEW_ATTACK_PATHS,
    PERMISSIONS.VIEW_WHAT_IF,
    PERMISSIONS.VIEW_RESPONSE,
    PERMISSIONS.VIEW_FORENSICS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_AUTHORIZATION,
    PERMISSIONS.EXECUTE_DEFENSIVE_ACTIONS,
    PERMISSIONS.ASSIGN_INCIDENTS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.MANAGE_DEVICES,
    PERMISSIONS.CONFIGURE_SECURITY
  ],

  [ROLES.SECURITY_ADMIN]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_DIGITAL_TWIN,
    PERMISSIONS.VIEW_ALERTS,
    PERMISSIONS.VIEW_INCIDENTS,
    PERMISSIONS.VIEW_AI_ANALYSIS,
    PERMISSIONS.VIEW_CYBER_DNA,
    PERMISSIONS.VIEW_ATTACK_PATHS,
    PERMISSIONS.VIEW_WHAT_IF,
    PERMISSIONS.VIEW_RESPONSE,
    PERMISSIONS.VIEW_FORENSICS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_AUTHORIZATION,
    PERMISSIONS.EXECUTE_DEFENSIVE_ACTIONS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.MANAGE_DEVICES,
    PERMISSIONS.CONFIGURE_SECURITY
  ],

  [ROLES.IT_ADMIN]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_DIGITAL_TWIN,
    PERMISSIONS.VIEW_ALERTS,
    PERMISSIONS.VIEW_CYBER_DNA,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_DEVICES
  ],

  [ROLES.INCIDENT_RESPONDER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ALERTS,
    PERMISSIONS.VIEW_INCIDENTS,
    PERMISSIONS.VIEW_AI_ANALYSIS,
    PERMISSIONS.VIEW_RESPONSE,
    PERMISSIONS.VIEW_FORENSICS,
    PERMISSIONS.EXECUTE_DEFENSIVE_ACTIONS
  ],

  [ROLES.SECURITY_AUDITOR]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ALERTS,
    PERMISSIONS.VIEW_INCIDENTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_AUDIT_LOGS
  ]
};

export function getPermissionsForRole(role) {
  return ROLE_PERMISSIONS[role] || ROLE_PERMISSIONS[ROLES.SOC_ANALYST];
}

export function hasRolePermission(role, permission) {
  const permissions = getPermissionsForRole(role);
  return permissions.includes(permission);
}
